version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /postgresql/data
    volumes:
      - ./postgresql/db-data:/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - ./pgadmin/pgadmin-data:/pgadmin-data
    links:
      - "db:pgsql-server"
    
  node:
    container_name: node_container
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./node:/node/
      - /node/node_modules
    ports:
      - "4000:8080"

  django:
    container_name: django_container
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  frontend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        container_name: hh-fortify-frontend
        ports:
            - "3000:3000"
        volumes: 
            - ./:/frontend
            - /frontend/node_modules

volumes:
  db-data:
  postgresql:
  pgadmin-data:
  django:
